#!/usr/bin/env bun

/**
 * CLI command: ov hooks-pi install|uninstall|status
 *
 * Manages orchestrator hooks for Pi (Google ADK).
 * Pi uses TypeScript extensions with factory functions - NOT shell commands.
 * 
 * According to Pi architecture analysis:
 * - Extensions are TypeScript modules with default export factory function
 * - Located in ~/.pi/agent/extensions/ or specified in settings.json
 * - 25+ lifecycle events available (tool_call, session_start, etc.)
 * - Can block tools via { block: true, reason: "..." }
 * - Event bus for inter-extension communication
 */

import { existsSync } from "node:fs";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { homedir } from "node:os";
import { Command } from "commander";
import { loadConfig } from "../config.ts";
import { ValidationError } from "../errors.ts";
import { jsonOutput } from "../json.ts";
import { printHint, printSuccess, printWarning } from "../logging/color.ts";

interface HookEntry {
	matcher: string;
	hooks: ReadonlyArray<{ type: string; command: string }>;
}

interface OverstoryHooksConfig {
	hooks: Record<string, HookEntry[]>;
}

interface PiSettings {
	extensions?: string[];
	packages?: string[];
	skills?: string[];
	prompts?: string[];
	themes?: string[];
}

/**
 * Get Pi agent directory path.
 */
function getPiAgentDir(): string {
	return join(homedir(), ".pi", "agent");
}

/**
 * Get Pi extensions directory.
 */
function getPiExtensionsDir(): string {
	return join(getPiAgentDir(), "extensions");
}

/**
 * Get Pi settings.json path.
 */
function getPiSettingsPath(): string {
	return join(getPiAgentDir(), "settings.json");
}

/**
 * Generate TypeScript extension for Pi.
 * 
 * Pi extensions use factory functions with ExtensionAPI.
 * This creates a comprehensive Overstory integration extension.
 */
function generatePiExtension(hooks: OverstoryHooksConfig): string {
	// Map Overstory events to Pi events
	const eventMappings = generateEventMappings(hooks);
	
	return `/**
 * Overstory Integration Extension for Pi (Google ADK)
 * 
 * Auto-generated by \`ov hooks-pi install\`
 * 
 * This extension integrates Overstory multi-agent orchestration with Pi,
 * providing mail injection, tool interception, logging, and session management.
 */

import type { ExtensionAPI, ExtensionContext } from "@mariozechner/pi-coding-agent";

// Overstory state management
interface OverstoryState {
	sessionInitialized: boolean;
	lastMailCheck: number;
	toolCallCount: Map<string, number>;
}

const state: OverstoryState = {
	sessionInitialized: false,
	lastMailCheck: 0,
	toolCallCount: new Map(),
};

/**
 * Execute Overstory command asynchronously.
 * Non-blocking - fires and forgets.
 */
async function runOvCommand(cmd: string, ctx?: ExtensionContext): Promise<void> {
	try {
		const { exec } = await import("child_process");
		const { promisify } = await import("util");
		const execAsync = promisify(exec);
		
		await execAsync(cmd, { 
			timeout: 30000,
			env: {
				...process.env,
				PI_PROJECT_DIR: process.cwd(),
			}
		});
	} catch (error) {
		// Silently ignore - don't disrupt Pi
		if (ctx) {
			ctx.logger?.debug?.("Overstory command failed", error);
		}
	}
}

/**
 * Extract tool name from tool call event.
 */
function getToolName(eventName: string, input: unknown): string {
	if (eventName === "tool_call") {
		const event = input as { toolName?: string };
		return event.toolName || "unknown";
	}
	return "unknown";
}

/**
 * Check if tool should be blocked.
 */
function shouldBlockTool(toolName: string, input: unknown): { block: boolean; reason?: string } {
	// Block dangerous git operations
	if (toolName === "bash") {
		const bashInput = input as { command?: string };
		const command = bashInput.command || "";
		
		if (command.includes("git push")) {
			// Log but don't block (user can override)
			runOvCommand("ov log git-push-attempted --agent orchestrator");
			return { 
				block: false, // Don't block, just warn
				reason: "git push detected - ensure you've merged locally first"
			};
		}
		
		if (command.includes("rm -rf /") || command.includes("sudo rm -rf")) {
			return { 
				block: true, 
				reason: "Dangerous command blocked by Overstory"
			};
		}
	}
	
	return { block: false };
}

/**
 * Get mail context for injection.
 */
async function getMailContext(): Promise<string> {
	try {
		const { exec } = await import("child_process");
		const { promisify } = await import("util");
		const execAsync = promisify(exec);
		
		const result = await execAsync("ov mail check --inject --agent orchestrator", {
			timeout: 10000
		});
		
		return result.stdout?.trim() || "No new messages";
	} catch {
		return "Mail check unavailable";
	}
}

/**
 * Initialize Overstory session.
 */
async function initializeSession(ctx: ExtensionContext): Promise<void> {
	if (state.sessionInitialized) return;
	
	state.sessionInitialized = true;
	await runOvCommand("ov prime --agent orchestrator", ctx);
	
	ctx.ui?.notify?.("Overstory initialized", "info");
}

/**
 * Cleanup Overstory session.
 */
async function cleanupSession(ctx: ExtensionContext): Promise<void> {
	await runOvCommand("ov log session-end --agent orchestrator", ctx);
	await runOvCommand("mulch learn", ctx);
	
	state.sessionInitialized = false;
}

/**
 * Main extension factory function.
 */
export default function (pi: ExtensionAPI) {
	const logger = {
		log: (msg: string) => console.log("[Overstory]", msg),
		debug: (msg: string, ...args: unknown[]) => console.debug("[Overstory]", msg, ...args),
		warn: (msg: string) => console.warn("[Overstory]", msg),
		error: (msg: string, err?: unknown) => console.error("[Overstory]", msg, err),
	};

	// ========================================
	// SESSION LIFECYCLE
	// ========================================

	/**
	 * Session Start - Initialize Overstory
	 */
	pi.on("session_start", async (_event, ctx) => {
		logger.log("Session started");
		await initializeSession(ctx);
		
		// Inject initial context
		const mailContext = await getMailContext();
		ctx.ui?.notify?.(mailContext, "info");
	});

	/**
	 * Session Shutdown - Cleanup
	 */
	pi.on("session_shutdown", async (_event, ctx) => {
		logger.log("Session shutting down");
		await cleanupSession(ctx);
	});

	// ========================================
	// USER PROMPT INTERCEPTION
	// ========================================

	/**
	 * Input - Check for new mail on user prompt
	 */
	pi.on("input", async (event, ctx) => {
		const now = Date.now();
		const MAIL_CHECK_INTERVAL = 5 * 60 * 1000; // 5 minutes
		
		if (now - state.lastMailCheck > MAIL_CHECK_INTERVAL) {
			state.lastMailCheck = now;
			const mailContext = await getMailContext();
			
			if (mailContext && mailContext !== "No new messages") {
				// Inject as context before agent starts
				pi.events.emit("overstory:mail_context", { context: mailContext });
			}
		}
	});

	/**
	 * Before Agent Start - Inject mail context
	 */
	pi.on("before_agent_start", async (event, ctx) => {
		// Check for mail context from input handler
		return new Promise((resolve) => {
			const mailHandler = (data: { context: string }) => {
				resolve({
					message: {
						customType: "overstory-mail",
						content: data.context,
						display: false, // Don't show to user
					}
				});
			};
			
			pi.events.once("overstory:mail_context", mailHandler);
			
			// Timeout after 2 seconds
			setTimeout(() => resolve({}), 2000);
		});
	});

	// ========================================
	// TOOL INTERCEPTION
	// ========================================

	/**
	 * Tool Call - Intercept and validate
	 */
	pi.on("tool_call", async (event, ctx) => {
		const toolName = event.toolName;
		const toolInput = event.input;
		
		// Track tool usage
		const count = state.toolCallCount.get(toolName) || 0;
		state.toolCallCount.set(toolName, count + 1);
		
		// Log tool start
		runOvCommand(\`ov log tool-start --agent orchestrator --tool-name $\{toolName}\`, ctx);
		
		// Check if should block
		const blockResult = shouldBlockTool(toolName, toolInput);
		if (blockResult.block) {
			logger.warn(\`Blocked tool: $\{toolName} - $\{blockResult.reason}\`);
			return { 
				block: true, 
				reason: blockResult.reason 
			};
		}
		
		if (blockResult.reason) {
			ctx.ui?.notify?.(blockResult.reason, "warning");
		}
	});

	/**
	 * Tool Result - Log completion
	 */
	pi.on("tool_result", async (event, ctx) => {
		const toolName = event.toolName;
		
		// Log tool end
		runOvCommand(\`ov log tool-end --agent orchestrator --tool-name $\{toolName}\`, ctx);
		
		// Auto-record learnings after git commit
		if (toolName === "bash") {
			const bashInput = event.input as { command?: string };
			if (bashInput?.command?.includes("git commit")) {
				runOvCommand("mulch diff HEAD~1", ctx);
			}
		}
	});

	// ========================================
	// CONTEXT MANAGEMENT
	// ========================================

	/**
	 * Context - Modify messages before LLM
	 */
	pi.on("context", async (event, ctx) => {
		// Could inject additional context here if needed
		// For now, we rely on before_agent_start
	});

	/**
	 * Before Compact - Prime context
	 */
	pi.on("session_before_compact", async (_event, ctx) => {
		await runOvCommand("ov prime --agent orchestrator --compact", ctx);
	});

	// ========================================
	// CUSTOM TOOLS (Optional)
	// ========================================

	/**
	 * Register Overstory status tool
	 */
	pi.registerTool({
		name: "overstory_status",
		label: "Overstory Status",
		description: "Check Overstory multi-agent orchestration status",
		parameters: {} as any, // Using Typebox would be better
		async execute(_toolCallId, _params, _signal, _onUpdate, ctx) {
			try {
				const { exec } = await import("child_process");
				const { promisify } = await import("util");
				const execAsync = promisify(exec);
				
				const result = await execAsync("ov status --json", { timeout: 10000 });
				const status = JSON.parse(result.stdout);
				
				return {
					content: [
						{ 
							type: "text", 
							text: \`Overstory Status:\\n$\{JSON.stringify(status, null, 2)}\` 
						}
					],
					details: {},
				};
			} catch (error) {
				return {
					content: [
						{ 
							type: "text", 
							text: \`Overstory status check failed: $\{error}\` 
						}
					],
					details: { error: String(error) },
					isError: true,
				};
			}
		},
	});

	/**
	 * Register mail check tool
	 */
	pi.registerTool({
		name: "overstory_mail",
		label: "Check Overstory Mail",
		description: "Check for new messages from other Overstory agents",
		parameters: {} as any,
		async execute(_toolCallId, _params, _signal, _onUpdate, ctx) {
			const mailContext = await getMailContext();
			
			return {
				content: [
					{ type: "text", text: mailContext }
				],
				details: {},
			};
		},
	});

	// ========================================
	// EVENT BUS INTEGRATION
	// ========================================

	/**
	 * Listen for custom Overstory events
	 */
	pi.events.on("overstory:checkpoint", (data) => {
		logger.debug("Checkpoint event received", data);
	});

	/**
	 * Emit session metrics
	 */
	pi.events.on("agent_end", () => {
		// Emit metrics for this turn
		pi.events.emit("overstory:turn_metrics", {
			toolCalls: Object.fromEntries(state.toolCallCount),
			timestamp: Date.now(),
		});
	});

	logger.log("Overstory extension loaded");
}
`;
}

/**
 * Generate event mappings from Overstory hooks.
 */
function generateEventMappings(hooks: OverstoryHooksConfig): string {
	const mappings: string[] = [];
	
	for (const [ovEvent, entries] of Object.entries(hooks.hooks)) {
		for (const entry of entries) {
			for (const hook of entry.hooks) {
				if (hook.command.includes("ov mail")) {
					mappings.push(`${ovEvent} → input/before_agent_start`);
				} else if (hook.command.includes("ov log tool-start")) {
					mappings.push(`${ovEvent} → tool_call`);
				} else if (hook.command.includes("ov log tool-end")) {
					mappings.push(`${ovEvent} → tool_result`);
				} else if (hook.command.includes("ov prime")) {
					mappings.push(`${ovEvent} → session_start/session_before_compact`);
				}
			}
		}
	}
	
	return mappings.join(", ");
}

/**
 * Install Overstory hooks for Pi.
 */
async function installHooksPi(force: boolean): Promise<void> {
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;

	// Read source hooks from .overstory/hooks.json
	const sourcePath = join(projectRoot, ".overstory", "hooks.json");
	const sourceFile = Bun.file(sourcePath);
	if (!(await sourceFile.exists())) {
		throw new ValidationError("No hooks.json found in .overstory/. Run 'ov init' first.", {
			field: "source",
		});
	}

	const sourceContent = await sourceFile.text();
	const sourceHooks = JSON.parse(sourceContent) as OverstoryHooksConfig;

	// Generate Pi extension
	const extensionCode = generatePiExtension(sourceHooks);

	// Get paths
	const piExtensionsDir = getPiExtensionsDir();
	const extensionPath = join(piExtensionsDir, "overstory-integration.ts");
	const settingsPath = getPiSettingsPath();

	// Create extensions directory if needed
	await mkdir(piExtensionsDir, { recursive: true });

	// Check if extension already exists
	if (!force && existsSync(extensionPath)) {
		console.log("Overstory extension already installed for Pi.");
		console.log("Use --force to overwrite.");
		return;
	}

	// Write extension
	await writeFile(extensionPath, extensionCode, "utf-8");
	
	printSuccess("Created Overstory extension");
	printHint(`  ${extensionPath}`);

	// Update settings.json to include extension
	let settings: PiSettings = {};
	
	if (existsSync(settingsPath)) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			settings = JSON.parse(content) as PiSettings;
		} catch {
			if (force) {
				printWarning("Existing settings.json is invalid, will create new");
			} else {
				throw new ValidationError("settings.json exists but is invalid. Use --force to overwrite.", {
					field: "settings",
				});
			}
		}
	}

	// Add extension path if not already present
	if (!settings.extensions) {
		settings.extensions = [];
	}

	// Use relative path with ~ instead of absolute path for portability
	const relativeExtensionPath = "~/.pi/agent/extensions/overstory-integration.ts";

	// Remove any absolute paths to this extension (cleanup from previous installs)
	settings.extensions = settings.extensions.filter(
		ext => !ext.includes("overstory-integration.ts")
	);

	// Add the relative path
	settings.extensions.push(relativeExtensionPath);

	await writeFile(settingsPath, JSON.stringify(settings, null, "\t"), "utf-8");
	printSuccess("Updated Pi settings");
	printHint(`  ${settingsPath}`);

	printHint("");
	printHint("Installed Pi events:");
	printHint("  - session_start → ov prime");
	printHint("  - input → ov mail check (periodic)");
	printHint("  - before_agent_start → inject mail context");
	printHint("  - tool_call → ov log tool-start + validation");
	printHint("  - tool_result → ov log tool-end");
	printHint("  - session_shutdown → ov log session-end + mulch learn");
	printHint("  - session_before_compact → ov prime --compact");
	printHint("");
	printHint("Registered tools:");
	printHint("  - overstory_status");
	printHint("  - overstory_mail");
	printHint("");
	printHint("Restart Pi for changes to take effect.");
}

/**
 * Install Mulch extension for Pi.
 * Copies mulch-pi-extension.ts to ~/.pi/agent/extensions/
 */
async function installMulchExtension(force: boolean): Promise<void> {
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;

	// Source: mulch/pi-extension/mulch-pi-extension.ts
	const sourcePath = join(projectRoot, "mulch", "pi-extension", "mulch-pi-extension.ts");
	const sourceFile = Bun.file(sourcePath);

	if (!(await sourceFile.exists())) {
		throw new ValidationError(
			`Mulch extension not found at ${sourcePath}. Ensure you're running from the overstory project root.`,
			{ field: "source" }
		);
	}

	// Get paths
	const piExtensionsDir = getPiExtensionsDir();
	const extensionPath = join(piExtensionsDir, "mulch-pi-extension.ts");
	const settingsPath = getPiSettingsPath();

	// Create extensions directory if needed
	await mkdir(piExtensionsDir, { recursive: true });

	// Check if extension already exists
	if (!force && existsSync(extensionPath)) {
		console.log("Mulch extension already installed for Pi.");
		console.log("Use --force to overwrite.");
		return;
	}

	// Read and write extension
	const extensionCode = await sourceFile.text();
	await writeFile(extensionPath, extensionCode, "utf-8");

	printSuccess("Created Mulch extension");
	printHint(`  ${extensionPath}`);

	// Update settings.json to include extension
	let settings: PiSettings = {};

	if (existsSync(settingsPath)) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			settings = JSON.parse(content) as PiSettings;
		} catch {
			if (force) {
				printWarning("Existing settings.json is invalid, will create new");
			} else {
				throw new ValidationError("settings.json exists but is invalid. Use --force to overwrite.", {
					field: "settings",
				});
			}
		}
	}

	// Add extension path if not already present
	if (!settings.extensions) {
		settings.extensions = [];
	}

	// Use relative path with ~ instead of absolute path for portability
	const relativeMulchExtensionPath = "~/.pi/agent/extensions/mulch-pi-extension.ts";

	// Remove any absolute paths to this extension (cleanup from previous installs)
	settings.extensions = settings.extensions.filter(
		ext => !ext.includes("mulch-pi-extension.ts")
	);

	// Add the relative path
	settings.extensions.push(relativeMulchExtensionPath);

	await writeFile(settingsPath, JSON.stringify(settings, null, "\t"), "utf-8");
	printSuccess("Updated Pi settings");
	printHint(`  ${settingsPath}`);

	printHint("");
	printHint("Mulch extension features:");
	printHint("  - session_start → ml prime (load expertise)");
	printHint("  - tool_result → auto-detect git commits");
	printHint("  - session_shutdown → ml learn (record changes)");
	printHint("");
	printHint("Registered tools:");
	printHint("  - mulch_record (record expertise)");
	printHint("  - mulch_query (query by domain)");
	printHint("  - mulch_search (semantic search)");
	printHint("  - mulch_prime (load context)");
	printHint("");
	printHint("Event bus integration:");
	printHint("  - overstory:* events");
	printHint("  - seeds:issue_closed");
	printHint("  - canopy:prompt_rendered");
	printHint("  - mulch:learning_recorded");
	printHint("  - mulch:suggest_learning");
	printHint("");
	printHint("Restart Pi for changes to take effect.");
}

/**
 * Remove Mulch extension from Pi.
 */
async function uninstallMulchExtension(): Promise<void> {
	const extensionPath = join(getPiExtensionsDir(), "mulch-pi-extension.ts");
	const settingsPath = getPiSettingsPath();

	// Remove extension file
	if (existsSync(extensionPath)) {
		await unlink(extensionPath);
		printSuccess("Removed Mulch extension");
	} else {
		printWarning("No Mulch extension found", "nothing to remove");
	}

	// Update settings.json
	if (existsSync(settingsPath)) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			const settings = JSON.parse(content) as PiSettings;

			if (settings.extensions) {
				const beforeLength = settings.extensions.length;
				settings.extensions = settings.extensions.filter(
					ext => !ext.includes("mulch")
				);

				if (settings.extensions.length < beforeLength) {
					await writeFile(settingsPath, JSON.stringify(settings, null, "\t"), "utf-8");
					printSuccess("Updated Pi settings");
				}
			}
		} catch (err) {
			printWarning("Failed to update settings.json", String(err));
		}
	}
}

/**
 * Show Mulch extension installation status.
 */
async function statusMulchExtension(json: boolean): Promise<void> {
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;

	const sourcePath = join(projectRoot, "mulch", "pi-extension", "mulch-pi-extension.ts");
	const extensionPath = join(getPiExtensionsDir(), "mulch-pi-extension.ts");
	const settingsPath = getPiSettingsPath();

	const sourceExists = await Bun.file(sourcePath).exists();
	const extensionExists = existsSync(extensionPath);

	let settingsHasExtension = false;

	if (existsSync(settingsPath)) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			const settings = JSON.parse(content) as PiSettings;

			if (settings.extensions) {
				settingsHasExtension = settings.extensions.some(
					ext => ext.includes("mulch")
				);
			}
		} catch {
			// Ignore parse errors
		}
	}

	if (json) {
		jsonOutput("mulch status", {
			sourceExists,
			extensionExists,
			settingsHasExtension,
		});
	} else {
		console.log(`Mulch extension source: ${sourceExists ? "✓ present" : "✗ missing"}`);
		console.log(`Mulch extension installed: ${extensionExists ? "✓ yes" : "✗ no"}`);
		console.log(`Pi settings.json: ${existsSync(settingsPath) ? "✓ exists" : "✗ missing"}`);
		console.log(`Extension in settings: ${settingsHasExtension ? "✓ yes" : "✗ no"}`);

		if (!extensionExists && sourceExists) {
			printHint("");
			printHint("Run ov hooks-pi install-mulch");
		}
	}
}

/**
 * Install Seeds extension for Pi.
 * Copies seeds-pi-extension.ts to ~/.pi/agent/extensions/
 */
async function installSeedsExtension(force: boolean): Promise<void> {
	// Source: ~/.pi/agent/extensions/seeds-pi-extension.ts (ya generada)
	// La extensión Seeds se genera directamente en el directorio de Pi
	const sourcePath = join(getPiExtensionsDir(), "seeds-pi-extension.ts");
	const sourceFile = Bun.file(sourcePath);

	if (!(await sourceFile.exists())) {
		throw new ValidationError(
			`Seeds extension not found at ${sourcePath}. Run 'ov hooks-pi generate-seeds' first.`,
			{ field: "source" }
		);
	}

	// Get paths
	const piExtensionsDir = getPiExtensionsDir();
	const extensionPath = join(piExtensionsDir(), "seeds-pi-extension.ts");
	const settingsPath = getPiSettingsPath();

	// Create extensions directory if needed
	await mkdir(piExtensionsDir, { recursive: true });

	// Check if extension already exists
	if (!force && existsSync(extensionPath)) {
		console.log("Seeds extension already installed for Pi.");
		console.log("Use --force to overwrite.");
		return;
	}

	// Update settings.json to include extension
	let settings: PiSettings = {};

	if (existsSync(settingsPath)) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			settings = JSON.parse(content) as PiSettings;
		} catch {
			if (force) {
				printWarning("Existing settings.json is invalid, will create new");
			} else {
				throw new ValidationError("settings.json exists but is invalid. Use --force to overwrite.", {
					field: "settings",
				});
			}
		}
	}

	// Add extension path if not already present
	if (!settings.extensions) {
		settings.extensions = [];
	}

	// Use relative path with ~ instead of absolute path for portability
	const relativeSeedsExtensionPath = "~/.pi/agent/extensions/seeds-pi-extension.ts";

	// Remove any absolute paths to this extension (cleanup from previous installs)
	settings.extensions = settings.extensions.filter(
		ext => !ext.includes("seeds-pi-extension.ts")
	);

	// Add the relative path
	settings.extensions.push(relativeSeedsExtensionPath);

	await writeFile(settingsPath, JSON.stringify(settings, null, "\t"), "utf-8");
	printSuccess("Updated Pi settings");
	printHint(`  ${settingsPath}`);

	printHint("");
	printHint("Seeds extension features:");
	printHint("  - session_start → sd ready (load issues)");
	printHint("  - tool_result → auto-refresh after sd commands");
	printHint("  - session_shutdown → check sync needed");
	printHint("");
	printHint("Registered tools:");
	printHint("  - seeds_create (create new issue)");
	printHint("  - seeds_list (list with filters)");
	printHint("  - seeds_status (get issue details)");
	printHint("  - seeds_update (update issue status)");
	printHint("  - seeds_prime (get workflow context)");
	printHint("");
	printHint("Event bus integration:");
	printHint("  - overstory:* events");
	printHint("  - mulch:learning_recorded");
	printHint("  - seeds:issue_created/updated/completed/blocked");
	printHint("");
	printHint("Restart Pi for changes to take effect.");
}

/**
 * Remove Seeds extension from Pi.
 */
async function uninstallSeedsExtension(): Promise<void> {
	const extensionPath = join(getPiExtensionsDir(), "seeds-pi-extension.ts");
	const settingsPath = getPiSettingsPath();

	// Remove extension file
	if (existsSync(extensionPath)) {
		await unlink(extensionPath);
		printSuccess("Removed Seeds extension");
	} else {
		printWarning("No Seeds extension found", "nothing to remove");
	}

	// Update settings.json
	if (existsSync(settingsPath)) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			const settings = JSON.parse(content) as PiSettings;

			if (settings.extensions) {
				const beforeLength = settings.extensions.length;
				settings.extensions = settings.extensions.filter(
					ext => !ext.includes("seeds")
				);

				if (settings.extensions.length < beforeLength) {
					await writeFile(settingsPath, JSON.stringify(settings, null, "\t"), "utf-8");
					printSuccess("Updated Pi settings");
				}
			}
		} catch (err) {
			printWarning("Failed to update settings.json", String(err));
		}
	}
}

/**
 * Show Seeds extension installation status.
 */
async function statusSeedsExtension(json: boolean): Promise<void> {
	const extensionPath = join(getPiExtensionsDir(), "seeds-pi-extension.ts");
	const settingsPath = getPiSettingsPath();

	const extensionExists = existsSync(extensionPath);

	let settingsHasExtension = false;

	if (existsSync(settingsPath)) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			const settings = JSON.parse(content) as PiSettings;

			if (settings.extensions) {
				settingsHasExtension = settings.extensions.some(
					ext => ext.includes("seeds")
				);
			}
		} catch {
			// Ignore parse errors
		}
	}

	if (json) {
		jsonOutput("seeds status", {
			extensionExists,
			settingsHasExtension,
		});
	} else {
		console.log(`Seeds extension installed: ${extensionExists ? "✓ yes" : "✗ no"}`);
		console.log(`Pi settings.json: ${existsSync(settingsPath) ? "✓ exists" : "✗ missing"}`);
		console.log(`Extension in settings: ${settingsHasExtension ? "✓ yes" : "✗ no"}`);

		if (!extensionExists) {
			printHint("");
			printHint("Run ov hooks-pi install-seeds");
		}
	}
}

/**
 * Remove Overstory hooks from Pi.
 */
async function uninstallHooksPi(): Promise<void> {
	const extensionPath = join(getPiExtensionsDir(), "overstory-integration.ts");
	const settingsPath = getPiSettingsPath();

	// Remove extension file
	if (existsSync(extensionPath)) {
		await unlink(extensionPath);
		printSuccess("Removed Overstory extension");
	} else {
		printWarning("No Overstory extension found", "nothing to remove");
	}

	// Update settings.json
	if (existsSync(settingsPath)) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			const settings = JSON.parse(content) as PiSettings;

			if (settings.extensions) {
				const beforeLength = settings.extensions.length;
				settings.extensions = settings.extensions.filter(
					ext => !ext.includes("overstory")
				);

				if (settings.extensions.length < beforeLength) {
					await writeFile(settingsPath, JSON.stringify(settings, null, "\t"), "utf-8");
					printSuccess("Updated Pi settings");
				}
			}
		} catch (err) {
			printWarning("Failed to update settings.json", String(err));
		}
	}
}

/**
 * Show hooks installation status for Pi.
 */
async function statusHooksPi(json: boolean): Promise<void> {
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;

	const sourcePath = join(projectRoot, ".overstory", "hooks.json");
	const extensionPath = join(getPiExtensionsDir(), "overstory-integration.ts");
	const settingsPath = getPiSettingsPath();

	const sourceExists = await Bun.file(sourcePath).exists();
	const extensionExists = existsSync(extensionPath);
	
	let settingsHasExtension = false;
	
	if (existsSync(settingsPath)) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			const settings = JSON.parse(content) as PiSettings;
			
			if (settings.extensions) {
				settingsHasExtension = settings.extensions.some(
					ext => ext.includes("overstory")
				);
			}
		} catch {
			// Ignore parse errors
		}
	}

	if (json) {
		jsonOutput("hooks status", {
			sourceExists,
			extensionExists,
			settingsHasExtension,
		});
	} else {
		console.log(`Hooks source (.overstory/hooks.json): ${sourceExists ? "✓ present" : "✗ missing"}`);
		console.log(`Overstory extension: ${extensionExists ? "✓ exists" : "✗ missing"}`);
		console.log(`Pi settings.json: ${existsSync(settingsPath) ? "✓ exists" : "✗ missing"}`);
		console.log(`Extension in settings: ${settingsHasExtension ? "✓ yes" : "✗ no"}`);
		
		if (!extensionExists && sourceExists) {
			printHint("");
			printHint("Run ov hooks-pi install");
		}
	}
}

export function createHooksPiCommand(): Command {
	const cmd = new Command("hooks-pi").description("Manage Overstory hooks for Pi (Google ADK)");

	cmd
		.command("install")
		.description("Install Overstory extension for Pi (TypeScript extension)")
		.option("--force", "Overwrite existing extension")
		.action(async (opts: { force?: boolean }) => {
			await installHooksPi(opts.force ?? false);
		});

	cmd
		.command("install-mulch")
		.description("Install Mulch expertise management extension for Pi")
		.option("--force", "Overwrite existing extension")
		.action(async (opts: { force?: boolean }) => {
			await installMulchExtension(opts.force ?? false);
		});

	cmd
		.command("install-all")
		.description("Install both Overstory and Mulch extensions for Pi")
		.option("--force", "Overwrite existing extensions")
		.action(async (opts: { force?: boolean }) => {
			await installHooksPi(opts.force ?? false);
			await installMulchExtension(opts.force ?? false);
		});

	cmd
		.command("install-seeds")
		.description("Install Seeds issue tracking extension for Pi")
		.option("--force", "Overwrite existing extension")
		.action(async (opts: { force?: boolean }) => {
			await installSeedsExtension(opts.force ?? false);
		});

	cmd
		.command("install-complete")
		.description("Install all extensions (Overstory + Mulch + Seeds) for Pi")
		.option("--force", "Overwrite existing extensions")
		.action(async (opts: { force?: boolean }) => {
			await installHooksPi(opts.force ?? false);
			await installMulchExtension(opts.force ?? false);
			await installSeedsExtension(opts.force ?? false);
		});

	cmd
		.command("uninstall")
		.description("Remove Overstory extension from Pi")
		.action(async () => {
			await uninstallHooksPi();
		});

	cmd
		.command("uninstall-mulch")
		.description("Remove Mulch extension from Pi")
		.action(async () => {
			await uninstallMulchExtension();
		});

	cmd
		.command("uninstall-seeds")
		.description("Remove Seeds extension from Pi")
		.action(async () => {
			await uninstallSeedsExtension();
		});

	cmd
		.command("uninstall-all")
		.description("Remove all extensions (Overstory + Mulch + Seeds) from Pi")
		.action(async () => {
			await uninstallHooksPi();
			await uninstallMulchExtension();
			await uninstallSeedsExtension();
		});

	cmd
		.command("status")
		.description("Check if Overstory extension is installed for Pi")
		.option("--json", "Output as JSON")
		.action(async (opts: { json?: boolean }) => {
			await statusHooksPi(opts.json ?? false);
		});

	cmd
		.command("status-mulch")
		.description("Check if Mulch extension is installed for Pi")
		.option("--json", "Output as JSON")
		.action(async (opts: { json?: boolean }) => {
			await statusMulchExtension(opts.json ?? false);
		});

	cmd
		.command("status-seeds")
		.description("Check if Seeds extension is installed for Pi")
		.option("--json", "Output as JSON")
		.action(async (opts: { json?: boolean }) => {
			await statusSeedsExtension(opts.json ?? false);
		});

	cmd
		.command("status-all")
		.description("Check installation status for all extensions")
		.option("--json", "Output as JSON")
		.action(async (opts: { json?: boolean }) => {
			await statusHooksPi(opts.json ?? false);
			console.log("");
			await statusMulchExtension(opts.json ?? false);
			console.log("");
			await statusSeedsExtension(opts.json ?? false);
		});

	return cmd;
}
