#!/usr/bin/env bun

/**
 * CLI command: ov hooks-qwen install|uninstall|status
 *
 * Manages orchestrator hooks for Qwen Code.
 * Qwen Code uses shell commands in .qwen/settings.json - NOT Python hooks.
 * 
 * According to Qwen Code architecture analysis:
 * - Hooks are shell commands executed via child_process.spawn
 * - Config is in .qwen/settings.json under "hooks" key
 * - 13 events available: PreToolUse, PostToolUse, UserPromptSubmit, SessionStart, etc.
 * - Hooks can intercept/modify tool calls and inject context
 */

import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { homedir } from "node:os";
import { Command } from "commander";
import { loadConfig } from "../config.ts";
import { ValidationError } from "../errors.ts";
import { jsonOutput } from "../json.ts";
import { printHint, printSuccess, printWarning } from "../logging/color.ts";

interface HookEntry {
	matcher: string;
	hooks: ReadonlyArray<{ type: string; command: string }>;
}

interface OverstoryHooksConfig {
	hooks: Record<string, HookEntry[]>;
}

interface QwenHookConfig {
	type: "command";
	name: string;
	command: string;
	timeout?: number;
	env?: Record<string, string>;
}

interface QwenHookDefinition {
	matcher?: string;
	sequential?: boolean;
	hooks: QwenHookConfig[];
}

interface QwenSettings {
	hooks?: Record<string, QwenHookDefinition[]>;
	hooksConfig?: {
		enabled?: boolean;
		disabled?: string[];
	};
}

/**
 * Get Qwen Code settings.json path.
 */
function getQwenSettingsPath(): string {
	return join(homedir(), ".qwen", "settings.json");
}

/**
 * Get Overstory hooks wrapper script path.
 */
function getOverstoryWrapperScriptPath(): string {
	return join(homedir(), ".qwen", "overstory-hooks-wrapper.py");
}

/**
 * Convert Overstory hooks to Qwen Code settings.json format.
 * 
 * Qwen Code uses shell commands, so we create a Python wrapper script
 * and configure settings.json to call it with appropriate arguments.
 */
function generateQwenHooksConfig(hooks: OverstoryHooksConfig): {
	settings: QwenSettings;
	wrapperScript: string;
} {
	// Generate wrapper Python script
	const wrapperScript = generateWrapperScript();
	
	// Generate settings.json hooks config
	const qwenHooks: Record<string, QwenHookDefinition[]> = {};
	
	const wrapperPath = getOverstoryWrapperScriptPath();
	
	// Map Overstory events to Qwen Code events
	const eventMapping: Record<string, string> = {
		"SessionStart": "SessionStart",
		"UserPromptSubmit": "UserPromptSubmit",
		"PreToolUse": "PreToolUse",
		"PostToolUse": "PostToolUse",
		"Stop": "Stop",
		"PreCompact": "PreCompact",
		"SessionEnd": "SessionEnd",
	};
	
	for (const [ovEvent, entries] of Object.entries(hooks.hooks)) {
		const qwenEvent = eventMapping[ovEvent];
		if (!qwenEvent) continue;
		
		const definitions: QwenHookDefinition[] = [];
		
		for (const entry of entries) {
			const hookConfigs: QwenHookConfig[] = [];
			
			for (const hook of entry.hooks) {
				// Skip complex bash commands that won't work
				if (hook.command.includes("read -r INPUT") || hook.command.includes("sed")) {
					continue;
				}
				
				// Convert ov command to wrapper script call
				const wrapperCommand = convertToWrapperCommand(hook.command, wrapperPath);
				if (!wrapperCommand) continue;
				
				hookConfigs.push({
					type: "command",
					name: `overstory-${ovEvent.toLowerCase()}-${hookConfigs.length}`,
					command: wrapperCommand,
					timeout: 30000,
					env: {
						"QWEN_PROJECT_DIR": "$QWEN_PROJECT_DIR",
					},
				});
			}
			
			if (hookConfigs.length > 0) {
				definitions.push({
					matcher: entry.matcher || "*",
					sequential: true,
					hooks: hookConfigs,
				});
			}
		}
		
		if (definitions.length > 0) {
			qwenHooks[qwenEvent] = definitions;
		}
	}
	
	const settings: QwenSettings = {
		hooks: qwenHooks,
		hooksConfig: {
			enabled: true,
			disabled: [],
		},
	};
	
	return { settings, wrapperScript };
}

/**
 * Generate Python wrapper script for Qwen Code hooks.
 * This script accepts CLI arguments and returns JSON for Qwen Code.
 */
function generateWrapperScript(): string {
	return `#!/usr/bin/env python3
"""
Overstory Hooks Wrapper for Qwen Code

Auto-generated by \`ov hooks-qwen install\`

This wrapper script executes Overstory commands and returns JSON
compatible with Qwen Code's hook system.
"""

import subprocess
import sys
import os
import json

def run_ov_command(cmd: str) -> dict:
    """Execute an overstory command and return result."""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            capture_output=True,
            text=True,
            timeout=30
        )
        return {
            "success": result.returncode == 0,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
            "returncode": result.returncode
        }
    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "stdout": "",
            "stderr": "Command timed out",
            "returncode": -1
        }
    except Exception as e:
        return {
            "success": False,
            "stdout": "",
            "stderr": str(e),
            "returncode": -1
        }

def get_mail_context():
    """Fetch mail context for UserPromptSubmit hook."""
    result = run_ov_command("ov mail check --inject --agent orchestrator")
    
    # Return context for Qwen Code
    if result["success"]:
        return {
            "hookSpecificOutput": {
                "hookEventName": "UserPromptSubmit",
                "additionalContext": result["stdout"] if result["stdout"] else "No new messages"
            }
        }
    else:
        return {
            "hookSpecificOutput": {
                "hookEventName": "UserPromptSubmit",
                "additionalContext": "Mail check unavailable"
            }
        }

def intercept_tool(tool_name: str, tool_input: dict = None):
    """Intercept tool calls for PreToolUse hook."""
    # Log tool usage
    run_ov_command(f"ov log tool-start --agent orchestrator --tool-name {tool_name}")
    
    # Check for dangerous commands
    if tool_name == "bash" and tool_input:
        command = tool_input.get("command", "")
        if "git push" in command:
            run_ov_command("ov log git-push-blocked --agent orchestrator")
            # Don't block, just log (Qwen Code doesn't support blocking via hooks)
    
    # Return continue signal
    return {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "tool_input": tool_input  # Pass through unchanged
        }
    }

def log_tool_end(tool_name: str):
    """Log tool completion for PostToolUse hook."""
    run_ov_command(f"ov log tool-end --agent orchestrator --tool-name {tool_name}")
    return {"success": True}

def session_init():
    """Initialize session for SessionStart hook."""
    run_ov_command("ov prime --agent orchestrator")
    return {
        "hookSpecificOutput": {
            "hookEventName": "SessionStart",
            "additionalContext": "Overstory initialized"
        }
    }

def session_end():
    """Cleanup session for Stop/SessionEnd hook."""
    run_ov_command("ov log session-end --agent orchestrator")
    run_ov_command("mulch learn")
    return {"success": True}

def pre_compact():
    """Handle context compaction for PreCompact hook."""
    run_ov_command("ov prime --agent orchestrator --compact")
    return {"success": True}

def main():
    if len(sys.argv) < 2:
        print(json.dumps({"error": "No command specified"}))
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == "get-mail-context":
        result = get_mail_context()
    elif command == "intercept-tool":
        tool_name = sys.argv[2] if len(sys.argv) > 2 else "unknown"
        tool_input = json.loads(sys.argv[3]) if len(sys.argv) > 3 else {}
        result = intercept_tool(tool_name, tool_input)
    elif command == "log-tool-end":
        tool_name = sys.argv[2] if len(sys.argv) > 2 else "unknown"
        result = log_tool_end(tool_name)
    elif command == "session-init":
        result = session_init()
    elif command == "session-end":
        result = session_end()
    elif command == "pre-compact":
        result = pre_compact()
    else:
        result = {"error": f"Unknown command: {command}"}
    
    print(json.dumps(result))
    sys.exit(0 if result.get("success", True) else 1)

if __name__ == "__main__":
    main()
`;
}

/**
 * Convert Overstory hook command to wrapper script call.
 */
function convertToWrapperCommand(ovCommand: string, wrapperPath: string): string | null {
	if (ovCommand.includes("ov mail check")) {
		return `python "${wrapperPath}" get-mail-context`;
	}
	if (ovCommand.includes("ov log tool-start")) {
		return `python "${wrapperPath}" intercept-tool "$TOOL_NAME" '$TOOL_INPUT'`;
	}
	if (ovCommand.includes("ov log tool-end")) {
		return `python "${wrapperPath}" log-tool-end "$TOOL_NAME"`;
	}
	if (ovCommand.includes("ov prime --agent orchestrator") && !ovCommand.includes("--compact")) {
		return `python "${wrapperPath}" session-init`;
	}
	if (ovCommand.includes("ov log session-end")) {
		return `python "${wrapperPath}" session-end`;
	}
	if (ovCommand.includes("ov prime --agent orchestrator --compact")) {
		return `python "${wrapperPath}" pre-compact`;
	}
	if (ovCommand.includes("mulch learn")) {
		return `mulch learn`;
	}
	
	// Skip commands we can't convert
	return null;
}

/**
 * Merge hooks into existing Qwen settings.
 */
function mergeHooks(existing: QwenSettings, newHooks: QwenSettings): QwenSettings {
	const merged: QwenSettings = {
		...existing,
		hooks: { ...existing.hooks },
	};
	
	if (newHooks.hooks) {
		for (const [event, definitions] of Object.entries(newHooks.hooks)) {
			const existingDefs = merged.hooks?.[event] || [];
			// Add new definitions, avoiding duplicates by name
			const existingNames = new Set(existingDefs.flatMap(d => d.hooks.map(h => h.name)));
			
			for (const def of definitions) {
				const newHooksToAdd = def.hooks.filter(h => !existingNames.has(h.name));
				if (newHooksToAdd.length > 0) {
					existingDefs.push({
						...def,
						hooks: newHooksToAdd,
					});
				}
			}
			
			if (existingDefs.length > 0) {
				merged.hooks![event] = existingDefs;
			}
		}
	}
	
	return merged;
}

/**
 * Install Overstory hooks for Qwen Code.
 */
async function installHooksQwen(force: boolean): Promise<void> {
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;

	// Read source hooks from .overstory/hooks.json
	const sourcePath = join(projectRoot, ".overstory", "hooks.json");
	const sourceFile = Bun.file(sourcePath);
	if (!(await sourceFile.exists())) {
		throw new ValidationError("No hooks.json found in .overstory/. Run 'ov init' first.", {
			field: "source",
		});
	}

	const sourceContent = await sourceFile.text();
	const sourceHooks = JSON.parse(sourceContent) as OverstoryHooksConfig;

	// Generate Qwen Code config
	const { settings: newHooks, wrapperScript } = generateQwenHooksConfig(sourceHooks);

	// Write wrapper script
	const wrapperPath = getOverstoryWrapperScriptPath();
	await mkdir(join(homedir(), ".qwen"), { recursive: true });
	await writeFile(wrapperPath, wrapperScript, "utf-8");
	
	printSuccess("Created wrapper script");
	printHint(`  ${wrapperPath}`);

	// Read existing settings.json
	const settingsPath = getQwenSettingsPath();
	let existingSettings: QwenSettings = {};
	
	if (existsSync(settingsPath)) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			existingSettings = JSON.parse(content) as QwenSettings;
		} catch (err) {
			if (force) {
				printWarning("Existing settings.json is invalid, will overwrite");
			} else {
				throw new ValidationError("settings.json exists but is invalid. Use --force to overwrite.", {
					field: "settings",
				});
			}
		}
	}

	// Merge hooks
	const mergedSettings = mergeHooks(existingSettings, newHooks);

	// Write updated settings
	await writeFile(settingsPath, JSON.stringify(mergedSettings, null, "\t"), "utf-8");
	
	printSuccess("Updated Qwen Code settings");
	printHint(`  ${settingsPath}`);
	printHint("");
	printHint("Installed hook events:");
	printHint("  - SessionStart → ov prime");
	printHint("  - UserPromptSubmit → ov mail check --inject");
	printHint("  - PreToolUse → ov log tool-start");
	printHint("  - PostToolUse → ov log tool-end");
	printHint("  - Stop → ov log session-end + mulch learn");
	printHint("  - PreCompact → ov prime --compact");
	printHint("");
	printHint("Restart Qwen Code for changes to take effect.");
}

/**
 * Remove Overstory hooks from Qwen Code.
 */
async function uninstallHooksQwen(): Promise<void> {
	const settingsPath = getQwenSettingsPath();
	const wrapperPath = getOverstoryWrapperScriptPath();

	if (!existsSync(settingsPath)) {
		printWarning("No Qwen Code settings.json found", "nothing to uninstall");
		return;
	}

	try {
		const content = await readFile(settingsPath, "utf-8");
		const settings = JSON.parse(content) as QwenSettings;
		
		// Remove Overstory hooks
		let removed = false;
		if (settings.hooks) {
			for (const event of Object.keys(settings.hooks)) {
				const defs = settings.hooks[event] || [];
				const filtered = defs.filter(def => 
					!def.hooks.some(h => h.name.startsWith("overstory-"))
				);
				
				if (filtered.length < defs.length) {
					settings.hooks[event] = filtered;
					removed = true;
				}
				
				// Remove empty event arrays
				if (filtered.length === 0) {
					delete settings.hooks[event];
				}
			}
		}
		
		if (removed) {
			await writeFile(settingsPath, JSON.stringify(settings, null, "\t"), "utf-8");
			printSuccess("Removed Overstory hooks from Qwen Code settings");
		} else {
			printWarning("No Overstory hooks found in settings", "nothing to remove");
		}
	} catch (err) {
		printWarning("Failed to read settings.json", String(err));
		return;
	}

	// Remove wrapper script
	if (existsSync(wrapperPath)) {
		await Bun.write(wrapperPath, "");
		await Bun.write(wrapperPath, ""); // Clear file
		printSuccess("Removed wrapper script");
	}
}

/**
 * Show hooks installation status for Qwen Code.
 */
async function statusHooksQwen(json: boolean): Promise<void> {
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;

	const sourcePath = join(projectRoot, ".overstory", "hooks.json");
	const settingsPath = getQwenSettingsPath();
	const wrapperPath = getOverstoryWrapperScriptPath();

	const sourceExists = await Bun.file(sourcePath).exists();
	const settingsExists = existsSync(settingsPath);
	const wrapperExists = existsSync(wrapperPath);
	
	let hooksInstalled = false;
	let overstoryHookCount = 0;
	
	if (settingsExists) {
		try {
			const content = await readFile(settingsPath, "utf-8");
			const settings = JSON.parse(content) as QwenSettings;
			
			if (settings.hooks) {
				for (const defs of Object.values(settings.hooks)) {
					for (const def of defs) {
						for (const hook of def.hooks) {
							if (hook.name.startsWith("overstory-")) {
								hooksInstalled = true;
								overstoryHookCount++;
							}
						}
					}
				}
			}
		} catch {
			// Ignore parse errors
		}
	}

	if (json) {
		jsonOutput("hooks status", {
			sourceExists,
			settingsExists,
			wrapperExists,
			hooksInstalled,
			overstoryHookCount,
		});
	} else {
		console.log(`Hooks source (.overstory/hooks.json): ${sourceExists ? "✓ present" : "✗ missing"}`);
		console.log(`Qwen settings.json: ${settingsExists ? "✓ exists" : "✗ missing"}`);
		console.log(`Wrapper script: ${wrapperExists ? "✓ exists" : "✗ missing"}`);
		console.log(`Overstory hooks: ${hooksInstalled ? `✓ ${overstoryHookCount} hooks configured` : "✗ none"}`);
		
		if (!hooksInstalled && sourceExists) {
			printHint("");
			printHint("Run ov hooks-qwen install");
		}
	}
}

export function createHooksQwenCommand(): Command {
	const cmd = new Command("hooks-qwen").description("Manage Overstory hooks for Qwen Code");

	cmd
		.command("install")
		.description("Install Overstory hooks for Qwen Code (writes to .qwen/settings.json)")
		.option("--force", "Overwrite existing hooks")
		.action(async (opts: { force?: boolean }) => {
			await installHooksQwen(opts.force ?? false);
		});

	cmd
		.command("uninstall")
		.description("Remove Overstory hooks from Qwen Code")
		.action(async () => {
			await uninstallHooksQwen();
		});

	cmd
		.command("status")
		.description("Check if Overstory hooks are installed for Qwen Code")
		.option("--json", "Output as JSON")
		.action(async (opts: { json?: boolean }) => {
			await statusHooksQwen(opts.json ?? false);
		});

	return cmd;
}
