/**
 * Overstory Integration Extension for Pi (Google ADK)
 *
 * Auto-generated by `ov hooks-pi install`
 *
 * This extension integrates Overstory multi-agent orchestration with Pi,
 * providing mail injection, tool interception, logging, and session management.
 *
 * Features:
 * - Activity tracking for Watchdog Tier 2 (prevents zombie classification)
 * - Mail check and send for inter-agent communication
 * - Tool interception with guard rules
 * - Context injection from mail
 * - Mulch learn integration
 */

import { existsSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, parse } from "node:path";
import type { ExtensionAPI, ExtensionContext } from "@mariozechner/pi-coding-agent";

// Overstory state management
interface OverstoryState {
	sessionInitialized: boolean;
	lastMailCheck: number;
	toolCallCount: Map<string, number>;
}

const state: OverstoryState = {
	sessionInitialized: false,
	lastMailCheck: 0,
	toolCallCount: new Map(),
};

const logger = {
	log: (msg: string) => console.log("[Overstory]", msg),
	debug: (msg: string, ...args: unknown[]) => console.debug("[Overstory]", msg, ...args),
	warn: (msg: string) => console.warn("[Overstory]", msg),
	error: (msg: string, err?: unknown) => console.error("[Overstory]", msg, err),
};

/**
 * Get the full path to overstory CLI.
 */
function getOvPath(): string {
	const home = homedir();
	const binName = process.platform === "win32" ? "ov.exe" : "ov";
	const bunBinPath = join(home, ".bun", "bin", binName);

	if (existsSync(bunBinPath)) return bunBinPath;
	return "ov";
}

/**
 * Find the project root by searching upwards for a .git directory.
 * Falls back to process.cwd() if no .git is found.
 */
function findProjectRoot(startDir: string = process.cwd()): string {
	let currentDir = startDir;
	const root = parse(currentDir).root;

	while (currentDir && currentDir !== root) {
		if (existsSync(join(currentDir, ".git"))) {
			return currentDir;
		}
		const parent = dirname(currentDir);
		if (parent === currentDir) break;
		currentDir = parent;
	}
	return startDir;
}

/**
 * Check if overstory CLI is available.
 */
async function isOverstoryAvailable(): Promise<boolean> {
	try {
		const { exec } = await import("child_process");
		const { promisify } = await import("util");
		const execAsync = promisify(exec);

		const ovPath = getOvPath();

		await execAsync(`"${ovPath}" --version`, {
			timeout: 5000,
		});
		return true;
	} catch {
		return false;
	}
}

/**
 * Execute Overstory command asynchronously.
 * Non-blocking - fires and forgets for background operations.
 */
async function runOvCommand(cmd: string, ctx?: ExtensionContext): Promise<void> {
	try {
		const { exec } = await import("child_process");
		const { promisify } = await import("util");
		const execAsync = promisify(exec);

		const ovPath = getOvPath();
		const fullCmd = cmd.replace(/^ov\b/, ovPath);

		const projectRoot = findProjectRoot();
		await execAsync(fullCmd, {
			timeout: 30000,
			cwd: projectRoot,
			env: {
				...process.env,
				PI_PROJECT_DIR: projectRoot,
			},
		});
	} catch (error) {
		// Silently ignore - don't disrupt Pi
		logger.debug("Overstory command failed", error);
	}
}

/**
 * Execute Overstory command and return output.
 * Blocking - returns stdout for tools that need responses.
 */
async function runOvCommandWithOutput(cmd: string, ctx?: ExtensionContext): Promise<string> {
	try {
		const { exec } = await import("child_process");
		const { promisify } = await import("util");
		const execAsync = promisify(exec);

		const ovPath = getOvPath();
		const fullCmd = cmd.replace(/^ov\b/, ovPath);

		const projectRoot = findProjectRoot();
		const result = await execAsync(fullCmd, {
			timeout: 30000,
			cwd: projectRoot,
			env: {
				...process.env,
				PI_PROJECT_DIR: projectRoot,
			},
		});

		return result.stdout?.trim() || "";
	} catch (error: any) {
		if (error.code === "ENOENT" || error.stderr?.includes("not recognized")) {
			logger.debug("Overstory CLI not found - command not available");
			throw new Error("Overstory CLI not found - run `bun install -g @os-eco/overstory-cli`");
		}
		logger.debug("Overstory command failed", error);
		throw error;
	}
}

/**
 * Attempt to extract JSON from potentially corrupted output.
 */
function extractJson(output: string): any {
	if (!output || output.trim() === "") {
		return { success: true, sessions: [] };
	}

	// Try direct parse first
	try {
		return JSON.parse(output);
	} catch {
		// Look for first { and last }
		const start = output.indexOf("{");
		const end = output.lastIndexOf("}");
		if (start !== -1 && end !== -1 && end > start) {
			const cleaned = output.substring(start, end + 1);
			try {
				return JSON.parse(cleaned);
			} catch {
				return { success: false, error: "Invalid JSON" };
			}
		}
		return { success: false, error: "Invalid JSON" };
	}
}

/**
 * Extract tool name from tool call event.
 */
function getToolName(eventName: string, input: unknown): string {
	if (eventName === "tool_call") {
		const event = input as { toolName?: string };
		return event.toolName || "unknown";
	}
	return "unknown";
}

/**
 * Check if tool should be blocked.
 */
function shouldBlockTool(toolName: string, input: unknown): { block: boolean; reason?: string } {
	// Block dangerous operations
	if (toolName === "bash") {
		const bashInput = input as { command?: string };
		const command = bashInput?.command || "";

		// Log git push attempts
		if (command.includes("git push")) {
			runOvCommand("ov log git-push-attempted --agent orchestrator");
			return {
				block: false, // Don't block, just warn
				reason: "git push detected - ensure you've merged locally first",
			};
		}

		// Block dangerous rm commands
		if (command.includes("rm -rf /") || command.includes("sudo rm -rf")) {
			return {
				block: true,
				reason: "Dangerous command blocked by Overstory",
			};
		}
	}

	return { block: false };
}

/**
 * Get mail context for injection.
 */
async function getMailContext(): Promise<string> {
	try {
		const { exec } = await import("child_process");
		const { promisify } = await import("util");
		const execAsync = promisify(exec);

		const result = await execAsync("ov mail check --inject --agent orchestrator", {
			timeout: 10000,
		});

		return result.stdout?.trim() || "No new messages";
	} catch {
		return "Mail check unavailable";
	}
}

/**
 * Initialize Overstory integration.
 */
async function initializeOverstory(ctx: ExtensionContext): Promise<void> {
	try {
		const overstoryAvailable = await isOverstoryAvailable();
		if (!overstoryAvailable) {
			logger.debug("Overstory CLI not found - skipping initialization");
			return;
		}

		// Check if .overstory/ directory exists
		const projectDir = findProjectRoot();
		const gitDirExists = existsSync(join(projectDir, ".git"));
		const ovDir = join(projectDir, ".overstory");
		const ovDirExists = existsSync(ovDir);

		logger.debug(
			`Initializing Overstory. Project Dir: ${projectDir}, Git Exists: ${gitDirExists}, Overstory Dir: ${ovDir}, Overstory Exists: ${ovDirExists}`,
		);

		if (!ovDirExists) {
			if (!gitDirExists) {
				logger.debug("No .git/ directory found - Overstory prefers a git repository");
				return;
			}

			// Auto-create directory
			try {
				logger.debug(`Auto-creating missing directory: ${ovDir}`);
				mkdirSync(ovDir, { recursive: true });
				ctx.ui?.notify?.(
					`Overstory: Created missing .overstory/ directory at ${ovDir}. Run \`ov init\` to complete setup.`,
					"info",
				);
			} catch (error) {
				logger.debug(`Failed to auto-create directory: ${ovDir}`, error);
				ctx.ui?.notify?.(
					`Overstory: No .overstory/ directory found at ${ovDir}. Run \`ov init\` to initialize.`,
					"info",
				);
			}
			return;
		}

		ctx.ui?.notify?.("Overstory initialized", "success");
		logger.log("Overstory integration initialized");
	} catch (error: any) {
		logger.debug("Failed to initialize Overstory", error);
	}
}

/**
 * Initialize Overstory session.
 */
async function initializeSession(ctx: ExtensionContext): Promise<void> {
	if (state.sessionInitialized) return;

	state.sessionInitialized = true;
	await runOvCommand("ov prime --agent orchestrator", ctx);

	ctx.ui?.notify?.("Overstory initialized", "info");
}

/**
 * Cleanup Overstory session.
 */
async function cleanupSession(ctx: ExtensionContext): Promise<void> {
	await runOvCommand("ov log session-end --agent orchestrator", ctx);
	await runOvCommand("mulch learn", ctx);

	state.sessionInitialized = false;
}

/**
 * Main extension factory function.
 */
export default function (pi: ExtensionAPI) {
	// ========================================
	// SESSION LIFECYCLE
	// ========================================

	/**
	 * Session Start - Initialize Overstory
	 */
	pi.on("session_start", async (_event, ctx) => {
		logger.log("Session started - initializing Overstory Integration");
		await initializeOverstory(ctx);
		await initializeSession(ctx);

		// Inject initial context
		const mailContext = await getMailContext();
		ctx.ui?.notify?.(mailContext, "info");
	});

	/**
	 * Session Shutdown - Cleanup and log activity
	 */
	pi.on("session_shutdown", async (_event, ctx) => {
		logger.log("Session shutting down");

		// Activity tracking for Watchdog Tier 2
		try {
			await runOvCommand("ov log activity --event session_shutdown", ctx);
			logger.debug("Activity logged: session_shutdown");
		} catch (error: any) {
			logger.debug("Failed to log session_shutdown activity", error);
		}

		await cleanupSession(ctx);
	});

	// ========================================
	// ACTIVITY TRACKING (Watchdog Tier 2)
	// ========================================

	/**
	 * Tool Execution End - Log activity to prevent zombie classification
	 */
	pi.on("tool_execution_end", async (event, ctx) => {
		// Log activity to prevent watchdog from marking as zombie
		try {
			await runOvCommand("ov log activity --event tool_execution", ctx);
			logger.debug("Activity logged: tool_execution");
		} catch (error: any) {
			// Silently ignore - activity logging is optional
			logger.debug("Failed to log tool_execution activity", error);
		}
	});

	// ========================================
	// USER PROMPT INTERCEPTION
	// ========================================

	/**
	 * Input - Check for new mail on user prompt
	 */
	pi.on("input", async (event, ctx) => {
		const now = Date.now();
		const MAIL_CHECK_INTERVAL = 5 * 60 * 1000; // 5 minutes

		if (now - state.lastMailCheck > MAIL_CHECK_INTERVAL) {
			state.lastMailCheck = now;
			const mailContext = await getMailContext();

			if (mailContext && mailContext !== "No new messages") {
				// Inject as context before agent starts
				pi.events.emit("overstory:mail_context", { context: mailContext });
			}
		}
	});

	/**
	 * Before Agent Start - Inject mail context
	 */
	pi.on("before_agent_start", async (event, ctx) => {
		// Check for mail context from input handler
		return new Promise((resolve) => {
			const mailHandler = (data: { context: string }) => {
				resolve({
					message: {
						customType: "overstory-mail",
						content: data.context,
						display: false, // Don't show to user
					},
				});
			};

			pi.events.once("overstory:mail_context", mailHandler);

			// Timeout after 2 seconds
			setTimeout(() => resolve({}), 2000);
		});
	});

	// ========================================
	// TOOL INTERCEPTION
	// ========================================

	/**
	 * Tool Call - Intercept and validate
	 */
	pi.on("tool_call", async (event, ctx) => {
		const toolName = event.toolName;
		const toolInput = event.input;

		// Track tool usage
		const count = state.toolCallCount.get(toolName) || 0;
		state.toolCallCount.set(toolName, count + 1);

		// Log tool start
		runOvCommand(`ov log tool-start --agent orchestrator --tool-name ${toolName}`, ctx);

		// Check if should block
		const blockResult = shouldBlockTool(toolName, toolInput);
		if (blockResult.block) {
			logger.warn(`Blocked tool: ${toolName} - ${blockResult.reason}`);
			return {
				block: true,
				reason: blockResult.reason,
			};
		}

		if (blockResult.reason) {
			ctx.ui?.notify?.(blockResult.reason, "warning");
		}
	});

	/**
	 * Tool Result - Log completion
	 */
	pi.on("tool_result", async (event, ctx) => {
		const toolName = event.toolName;

		// Log tool end
		runOvCommand(`ov log tool-end --agent orchestrator --tool-name ${toolName}`, ctx);

		// Auto-record learnings after git commit
		if (toolName === "bash") {
			const bashInput = event.input as { command?: string };
			if (bashInput?.command?.includes("git commit")) {
				runOvCommand("mulch diff HEAD~1", ctx);
			}
		}
	});

	// ========================================
	// CONTEXT MANAGEMENT
	// ========================================

	/**
	 * Context - Modify messages before LLM
	 */
	pi.on("context", async (event, ctx) => {
		// Could inject additional context here if needed
		// For now, we rely on before_agent_start
	});

	/**
	 * Before Compact - Prime context
	 */
	pi.on("session_before_compact", async (_event, ctx) => {
		await runOvCommand("ov prime --agent orchestrator --compact", ctx);
	});

	// ========================================
	// CUSTOM TOOLS
	// ========================================

	/**
	 * overstory_status - Get Overstory status
	 */
	pi.registerTool({
		name: "overstory_status",
		label: "Get Overstory Status",
		description: "Get the status of the Overstory ecosystem and active sessions",
		parameters: {
			type: "object",
			properties: {},
		} as any,
		async execute(_toolCallId, _params, _signal, _onUpdate, ctx) {
			try {
				const output = await runOvCommandWithOutput("ov status --json", ctx);
				const status = extractJson(output);

				return {
					content: [
						{
							type: "text",
							text: `Overstory Status: ${status.success ? "Online" : "Offline"}\nSessions: ${status.sessions?.length || 0}`,
						},
					],
					details: status,
				};
			} catch (error) {
				return {
					content: [
						{
							type: "text",
							text: `Failed to get status: ${error}`,
						},
					],
					isError: true,
				};
			}
		},
	});

	/**
	 * overstory_mail - Send mail to another agent
	 */
	pi.registerTool({
		name: "overstory_mail",
		label: "Send Overstory Mail",
		description: "Send a message to another agent via Overstory mail system",
		parameters: {
			type: "object",
			properties: {
				to: { type: "string", description: "Recipient agent name" },
				subject: { type: "string", description: "Message subject" },
				body: { type: "string", description: "Message body" },
			},
			required: ["to", "body"],
		} as any,
		async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
			try {
				const { to, subject = "Message", body } = params;
				// Escape double quotes for shell command
				const escapedBody = body.replace(/"/g, '\\"');
				const escapedSubject = subject.replace(/"/g, '\\"');

				await runOvCommandWithOutput(
					`ov mail send --to "${to}" --subject "${escapedSubject}" --body "${escapedBody}"`,
					ctx,
				);

				return {
					content: [
						{
							type: "text",
							text: `✓ Mail sent to ${to}`,
						},
					],
				};
			} catch (error: any) {
				return {
					content: [
						{
							type: "text",
							text: `Failed to send mail: ${error}`,
						},
					],
					isError: true,
				};
			}
		},
	});

	/**
	 * overstory_mail_check - Check for new mail
	 */
	pi.registerTool({
		name: "overstory_mail_check",
		label: "Check Overstory Mail",
		description: "Check for new messages from other Overstory agents",
		parameters: {} as any,
		async execute(_toolCallId, _params, _signal, _onUpdate, ctx) {
			try {
				const mailContext = await getMailContext();
				return {
					content: [{ type: "text", text: mailContext }],
					details: {},
				};
			} catch (error: any) {
				return {
					content: [{ type: "text", text: `Mail check failed: ${error}` }],
					isError: true,
				};
			}
		},
	});

	// ========================================
	// CUSTOM COMMANDS (UI Integration)
	// ========================================

	/**
	 * /overstory - Overstory multi-agent commands
	 */
	pi.registerCommand("overstory", {
		description: "Overstory multi-agent orchestration",
		getArgumentCompletions: (prefix: string) => {
			const subcommands = ["status", "mail", "prime", "merge", "sling", "doctor"];
			const filtered = subcommands.filter((s: string) => s.startsWith(prefix));
			return filtered.length > 0 ? filtered.map((s) => ({ value: s, label: s })) : null;
		},
		handler: async (args: string, ctx) => {
			const parts = args.trim().split(/\s+/);
			const subcommand = parts[0] || "";

			try {
				let output: string;

				switch (subcommand) {
					case "status":
						output = await runOvCommandWithOutput("ov status", ctx);
						break;
					case "mail":
						const mailArgs = parts.slice(1).join(" ");
						if (mailArgs.includes("--to")) {
							output = await runOvCommandWithOutput(`ov mail send ${mailArgs}`, ctx);
						} else {
							output = await runOvCommandWithOutput("ov mail check", ctx);
						}
						break;
					case "prime":
						output = await runOvCommandWithOutput("ov prime --agent orchestrator", ctx);
						break;
					case "merge":
						output = await runOvCommandWithOutput("ov merge", ctx);
						break;
					case "sling":
						const slingArgs = parts.slice(1).join(" ");
						output = await runOvCommandWithOutput(`ov sling ${slingArgs}`, ctx);
						break;
					case "doctor":
						output = await runOvCommandWithOutput("ov doctor", ctx);
						break;
					case "":
						// Show status by default
						output = await runOvCommandWithOutput("ov status", ctx);
						break;
					default:
						ctx.ui?.notify?.(`Unknown subcommand: ${subcommand}`, "warning");
						ctx.ui?.notify?.("Available: status, mail, prime, merge, sling, doctor", "info");
						return;
				}

				ctx.ui?.notify?.(output || "Command executed", "info");
			} catch (error: any) {
				ctx.ui?.notify?.(`Overstory error: ${error.message}`, "error");
			}
		},
	});

	// ========================================
	// EVENT BUS INTEGRATION
	// ========================================

	/**
	 * Listen for custom Overstory events
	 */
	pi.events.on("overstory:checkpoint", (data) => {
		logger.debug("Checkpoint event received", data);
	});

	/**
	 * Emit session metrics
	 */
	pi.events.on("agent_end", () => {
		// Emit metrics for this turn
		pi.events.emit("overstory:turn_metrics", {
			toolCalls: Object.fromEntries(state.toolCallCount),
			timestamp: Date.now(),
		});
	});

	logger.log("Overstory extension loaded");
}
